wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 1
      - 3
      2:
      - 1
      - 3
      3:
      - 2
      4: 3.8.3
      5: 0.10.32
      8:
      - 6
env:
  desc: null
  value: Neural_MMO
env_config:
  desc: null
  value:
    config: <projekt.config.CompetitionRound1 object at 0x7ffbd46ca490>
evaluation_config:
  desc: null
  value:
    env_config:
      config: <projekt.config.CompetitionRound1 object at 0x7ffbd46ca520>
evaluation_interval:
  desc: null
  value: 1
evaluation_num_episodes:
  desc: null
  value: 1
evaluation_num_workers:
  desc: null
  value: 1
evaluation_parallel_to_training:
  desc: null
  value: true
framework:
  desc: null
  value: torch
horizon:
  desc: null
  value: .inf
model:
  desc: null
  value:
    custom_model: godsword
    custom_model_config:
      config: <projekt.config.CompetitionRound1 object at 0x7ffbd46ca490>
    max_seq_len: 16
multiagent:
  desc: null
  value:
    count_steps_by: agent_steps
    policies:
      policy_0: '(None, FlexDict(Entity:FlexDict(Continuous:Box(100, 13), Discrete:Box(100,
        4), N:Box(1,)), Tile:FlexDict(Continuous:Box(225, 4), Discrete:Box(225, 3))),
        FlexDict(<class ''neural_mmo.forge.blade.io.action.static.Attack''>:FlexDict(<class
        ''neural_mmo.forge.blade.io.action.static.Style''>:Discrete(3), <class ''neural_mmo.forge.blade.io.action.static.Target''>:Discrete(100)),
        <class ''neural_mmo.forge.blade.io.action.static.Move''>:FlexDict(<class ''neural_mmo.forge.blade.io.action.static.Direction''>:Discrete(4))),
        {''agent_id'': 0, ''obs_space_dict'': FlexDict(Entity:FlexDict(Continuous:Box(100,
        13), Discrete:Box(100, 4), N:Box(1,)), Tile:FlexDict(Continuous:Box(225, 4),
        Discrete:Box(225, 3))), ''act_space_dict'': FlexDict(<class ''neural_mmo.forge.blade.io.action.static.Attack''>:FlexDict(<class
        ''neural_mmo.forge.blade.io.action.static.Style''>:Discrete(3), <class ''neural_mmo.forge.blade.io.action.static.Target''>:Discrete(100)),
        <class ''neural_mmo.forge.blade.io.action.static.Move''>:FlexDict(<class ''neural_mmo.forge.blade.io.action.static.Direction''>:Discrete(4)))})'
    policy_mapping_fn: <function run_tune_experiment.<locals>.<lambda> at 0x7ffbd42ed8b0>
no_done_at_end:
  desc: null
  value: false
num_envs_per_worker:
  desc: null
  value: 1
num_gpus:
  desc: null
  value: 0
num_gpus_per_worker:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 1
render_env:
  desc: null
  value: true
rollout_fragment_length:
  desc: null
  value: 256
sgd_minibatch_size:
  desc: null
  value: 128
soft_horizon:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 458752
